CREATE TABLE JOB_STEPS_CONFIG(
  SYSTEM_SK VARCHAR2(3 BYTE)
, SUBSYSTEM_SK VARCHAR2(3 BYTE)
, JOB_ID NUMBER(10,0)
, STEP_NUMBER NUMBER(10,0)
, OPERATION_TYPE CHAR(1)
, OPERATION_NAME VARCHAR2(128)
, OPERATION_TAG VARCHAR2(128)
, OPERATION_VALUE VARCHAR2(4000)
, OPERATION_ORDER NUMBER(10,0)
, OPERATION_SUB_ORDER NUMBER(10,0)
, ACTIVE_FLAG CHAR(1) DEFAULT 'Y'
, PROCESS_COMPLETED CHAR(1) DEFAULT 'N'
, CREATE_TIME TIMESTAMP
, CREATE_BY VARCHAR2(128)
);




INSERT INTO JOB_STEPS_CONFIG VALUES('000', '000', 1,2, 'P', 'BATCH_CDC', 'p_table_owner', 'INFA_SRC', 1, 1, 'Y', 'N', SYSTIMESTAMP, USER);
INSERT INTO JOB_STEPS_CONFIG VALUES('000', '000', 1,2, 'P', 'BATCH_CDC', 'p_stage_table ', 'SALARY_DATA_STG', 1, 2, 'Y', 'N', SYSTIMESTAMP, USER);
INSERT INTO JOB_STEPS_CONFIG VALUES('000', '000', 1,2, 'P', 'BATCH_CDC', 'p_cdc_table', 'SALARY_DATA_CDC', 1, 3, 'Y', 'N', SYSTIMESTAMP, USER);
INSERT INTO JOB_STEPS_CONFIG VALUES('000', '000', 1,2, 'P', 'BATCH_CDC', 'p_target_table', 'SALARY_DATA', 1, 4, 'Y', 'N', SYSTIMESTAMP, USER);


INSERT INTO JOB_STEPS_CONFIG VALUES('000', '000', 1,1, 'L', 'SQLLDR', 'p_control_file_path', '/prod/sqlldrs/', 1, 1, 'Y', 'N', SYSTIMESTAMP, USER);
INSERT INTO JOB_STEPS_CONFIG VALUES('000', '000', 1,1, 'L', 'SQLLDR', 'p_control_file_name', 'SALARY_DATA_STG.ctl', 1, 2, 'Y', 'N', SYSTIMESTAMP, USER);
INSERT INTO JOB_STEPS_CONFIG VALUES('000', '000', 1,1, 'L', 'SQLLDR', 'p_target_table', 'SALARY_DATA_STG', 2, 1, 'Y', 'N', SYSTIMESTAMP, USER);


select * from job_steps_config where job_id = :p_job_id
and active_flag = 'Y' and process_completed = 'N'
order by step_number, operation_order, operation_sub_order;
