CREATE TABLE "INFA_SRC"."CONTROL_REPS" (
    "REP_ID" VARCHAR2(10 BYTE), 
	"SEQ_NUMBER" NUMBER, 
	"CREATE_DATE" DATE, 
	"TXT_LINE" VARCHAR2(4000 BYTE), 
	 CONSTRAINT "CREP_PK" PRIMARY KEY ("REP_ID", "SEQ_NUMBER")
)
