create table infa_global_fix(
    STATEMENT_PRD_YR_QRTR CHAR(6 BYTE)
    , RUN_DTE DATE
    , SOQ_DTE DATE
    , EOQ_DTE DATE
    , LAST_UPDATE_DTE DATE
    , LAST_UPDATED_BY VARCHAR2(30)
    , BIN2_IND CHAR(1 BYTE) DEFAULT 'N'
	, BIN3_IND CHAR(1 BYTE) DEFAULT 'N'
	, BIN4_IND CHAR(1 BYTE) DEFAULT 'N'
	, BIN5_IND CHAR(1 BYTE) DEFAULT 'N'
);
