CREATE TABLE ARCHIVE_RULES(
 TABLE_OWNER         VARCHAR2(128), 
 TABLE_NAME          VARCHAR2(128), 
 PARTITIONED         CHAR(1), 
 YEARS_TO_KEEP       NUMBER(3,0), 
 UPD_FLAG            CHAR(1) DEFAULT 'N', 
 ARCHIVE_COLUMN_KEY  VARCHAR2(128), 
 JOB_NBR             NUMBER(2,0) DEFAULT NULL, 
 CONSTRAINT ARC_PERSIST CHECK (YEARS_TO_KEEP > 1) ENABLE, 
 CONSTRAINT ARC_PK PRIMARY KEY ("TABLE_OWNER", "TABLE_NAME")
 );
