CREATE TABLE PARTITION_TABLE_PARM  (
     TABLE_OWNER      VARCHAR2(128), 
     TABLE_NAME       VARCHAR2(128), 
     PARTITIONED      CHAR(1), 
     TABLESPACE_NAME  VARCHAR2(30), 
     PARTITION_TYPE   CHAR(1), 
     PARTITION_PREFIX VARCHAR2(4), 
     UPD_FLAG         CHAR(1) DEFAULT 'N', 
     CONSTRAINT "PTP_PK" PRIMARY KEY ("TABLE_OWNER", "TABLE_NAME")
);


/* OLD
CREATE TABLE PARTITION_TABLE_PARM  (
     TABLE_OWNER      VARCHAR2(128), 
     TABLE_NAME       VARCHAR2(128), 
     PARTITIONED      CHAR(1), 
     TABLESPACE_NAME  VARCHAR2(30), 
     PARTITION_TYPE   CHAR(1), 
     PARTITION_PREFIX VARCHAR2(4), 
     YEARS_TO_KEEP    NUMBER(3,0), 
     UPD_FLAG         CHAR(1) DEFAULT 'N', 
     CONSTRAINT "PTP_PERSIST" CHECK (YEARS_TO_KEEP > 1) ENABLE, 
     CONSTRAINT "PTP_PK" PRIMARY KEY ("TABLE_OWNER", "TABLE_NAME")
);*/
