CREATE TABLE update_match (
     TABLE_OWNER        VARCHAR2(128) NOT NULL ENABLE, 
     TABLE_NAME         VARCHAR2(128) NOT NULL ENABLE, 
     COLUMN_NAME        VARCHAR2(128) NOT NULL ENABLE, 
     SORT_ORDER_NUMBER  NUMBER(3,0) NOT NULL ENABLE, 
     CONSTRAINT "UPD_MATCH_PK" PRIMARY KEY ("TABLE_OWNER", "TABLE_NAME", "COLUMN_NAME")
);
